### ISSUE TITLE
Improve Readme

### ISSUE THREAD

**Issue by CodeFetch** [mrkiko/agh#2]
I can't find any information about for what this is useful.
The README should give some examples. From what I've learned, the future of UI development is all web-based. Why do you use XMPP for that instead of giving the user a GUI? 
For running commands etc. like in a console, one uses a SSH session. For automation one uses a SSL encrypted JSON REST API (which can be done with uBUS already).

The "what" is explained thoroughly, but not the "why"... For a non-mainstream project there always need to be "latent needs" to become successful. It's not clear why I should need this. A proper, easy-to-use modem manager with good Luci interface would be great for OpenWrt (that's why I clicked the link in your email), but I think this is not what this project is about.

Just make clear what you want to achieve here, what problems your project solves and why I should want to use it.

By the way... Your coding style is awesome.

**Comment by mrkiko** [comment]
Hello @CodeFetch and thank you very very much for your comment!
So, the idea behind AGH is to have a Modem connection manager with extended capabilities, and an XMPP bot you may use to control your device remotely.
The idea is to have the device initiate the connection, since it may well be behind multiple NATs, as is usually the case when in cellular networks.
I used XMPP because I tought it would be a good protocol / choice, offering scalability from the ground up.
I am open to changing this aspect as well - and the architecture of AGH should allow for implementing other connection means.
You may decide to use AGH only as a bot, or only as a connection manager. I was also thinking about allowing to compile out functionalities.

Regarding modem management, when I say "extended capabilities", I mean that AGH may be configured to e.g.: define and connect 2 bearers with modem A, 1 bearer with modem B, and 1 with modem C, setting modem C to prefer 4G.


Well, implementing a LUCI interface and a CLI GUI are all things I would like to do very much.
AGH interacts with UCI via libuci directly, and runs as a service, so it should be pretty feasible!

May I ask you how I may explain this on the README in a concise and clear form?
Thank you again for your help and comments.

**Comment by mrkiko** [comment]
@CodeFetch oh - and thank you for your words!
And again - for your help. Making this project useful is very important to me. So any chance to make it clear what it's purpose is, is especially important. :)

**Comment by mrkiko** [comment]
@CodeFetch oh - sorry for the comment storm.
As per the future of AGH - I think it'll be driven by it's users and developers.
I developed functionalities I needed / wanted the most, but there is no strictly fixed roadmap.
Of course, fixing bugs and making the software as stable, robust and secure as possible, is a priority. As it a priority making the software useful :) so thanks again for pointing this out.
